### PR TITLE
Enable cocoapod creation for this repo

### PR DESCRIPTION
**Pull request by shankari**
This fixes #8.

The real changes are in `TCNClient.podspec`.
The standard command to create a pod also allows you to create an example of
using the pod.

I am not sure this is useful for this library, but it is easier to delete the example than to reconstruct it using boilerplate later.

Testing done:

pod itself compiles

```
tcn-client-ios shankari$ pod lib lint TCNClient.podspec --allow-warnings

 -> TCNClient (0.1.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - WARN  | [iOS] xcodebuild:  /Users/shankari/OSS/tcn-client-ios/Sources/TCNClient/Crypto/DataRepresentable.swift:34:29: warning: initialization of 'UnsafeBufferPointer<Self>' results in a dangling buffer pointer
    - NOTE  | [iOS] xcodebuild:  /Users/shankari/OSS/tcn-client-ios/Sources/TCNClient/Crypto/DataRepresentable.swift:34:56: note: implicit argument conversion from 'Self' to 'UnsafePointer<Self>?' produces a pointer valid only for the duration of the call to 'init(start:count:)'
    - NOTE  | [iOS] xcodebuild:  /Users/shankari/OSS/tcn-client-ios/Sources/TCNClient/Crypto/DataRepresentable.swift:34:56: note: use 'withUnsafePointer' in order to explicitly convert argument to pointer valid for a defined scope
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'TCNClient' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'App' from project 'App')

TCNClient passed validation.
```

demo project compiles (see screenshot in PR)

Screen Shot 2020-04-14 at 10 38 43 PM

### CODE REVIEW

**Comment by shankari** [comment]
This fixes #8

**Comment by shankari** [comment]
@tzachari, I am not sure whether this is the equivalent of the `libcen` code on android. In particular, I don't see any scanner or advertiser interfaces. Is this actually a full replacement for the current code, or do we need to pull in any other iOS code?

**Comment by shankari** [comment]
@zssz @tzachari can you please review?
@zssz after you merge this change, you probably want to publish it. I'll be happy to walk you through the steps, but I think that the binaries should live under the CovidWatch account.

**Comment by tzachari** [comment]
> @tzachari, I am not sure whether this is the equivalent of the `libcen` code on android. In particular, I don't see any scanner or advertiser interfaces. Is this actually a full replacement for the current code, or do we need to pull in any other iOS code?

**tcn-client-ios** does look to be mostly equivalent. 

It just doesn't expose separate calls to the scanner and advertiser interfaces, which I think is better since both are always expected to be initiated and halted at the same time. 

`centralManager` and `peripheralManager` are the scanner and advertiser interfaces, but they are only [called internally](https://github.com/TCNCoalition/tcn-client-ios/blob/0.4.1/Sources/TCNClient/Bluetooth/TCNBluetoothServiceImpl.swift#L204).

The Android library is actually [calling them internally now](https://github.com/TCNCoalition/tcn-client-android/blob/0.0.1/tcn-client-android/src/main/java/org/tcncoalition/tcnclient/BluetoothService.kt#L40) too, which seems to make additional calls to `startScanner` or `startAdvertiser` extraneous.

**covidwatch-android** actually doesn't [call them separately anymore](https://github.com/covid19risk/covidwatch-android/blob/82d26d726c083cebcd0d7951f5c1b0febc4fd999/app/src/main/java/org/covidwatch/android/CovidWatchApplication.kt) either, even though there are associated methods defined in the [BluetoothManager implementation](https://github.com/covid19risk/covidwatch-android/blob/82d26d726c083cebcd0d7951f5c1b0febc4fd999/app/src/main/java/org/covidwatch/android/ble/BluetoothManager.kt).

So, if anything, those methods should probably be made private in the Android library and removed from the Android app.

I will test the pod later today. Thanks!

**Review by tzachari — APPROVED** [review]
This looks good for the most part. 

The example project works for me, but it probably isn't necessary to pull it into the repo. 

I also tested using the pod installation as a replacement for the iOS source of the Cordova plugin. Seems to be working well! But, it definitely will be a cleaner process once it's published as an official Pod.

Thanks!

**Comment by zssz** [comment]
I finally got to review this PR, @shankari. It looks great and I think adding CocoaPods support is needed! In the Covid Watch iOS app we use Swift Packages.

Can you remove the sample app and the Xcode project? I don't understand the purpose of those.

**Comment by parametr** [comment]
I agree that for now we don't need to have example project as this protocol implementation will likely be wrapped into other apps or frameworks which will serve as demo apps for it. I guess contributors to this repo will not have time to create a demo/example app just for this library...

I did added .podspec in my fork just to be able to embed it in our app as Cocoapod. I removed all the clutter from Example and left only concise `podspec` - https://github.com/EQWorks/tcn-client-ios/commit/da0c3eca4003a2dfc7feae7ca4e30eade3299253. I haven't created PR for it because I saw this PR existed.

I would recommend either reducing this PR to a single podspec file or just merge the commit from my fork as is.

**Comment by shankari** [comment]
@zssz the cocoapod creation script offered to automatically add an example app for better automated testing. I wasn't sure of the direction that the project wanted to take and figured that it would be easier to remove code than to add it. 

Removing it now...

**Comment by shankari** [comment]
Done. Make sure to squash-merge to ensure that the commit history is not polluted.

**Comment by shankari** [comment]
@zssz 🙋 it's been a week since I made the requested changes, so just checking back to see whether you need anything else before merging... 🤔

**Comment by zssz** [comment]
Hey! Thank you for the nudge. I just merged this.

**Comment by shankari** [comment]
@zssz are you also planning to publish this as a pod in the cocoapod registry? I think you should do that instead of @parametr or me to make them more "official".

**Pull request merged**
